/**
 * Default site content — the exact copy of the approved mockup (V3).
 * Used to seed MongoDB and as a fallback when a document is missing, so the site
 * always renders the approved design. Editable from the dashboard afterwards.
 * Author: Avijit Ghosh
 */
import type {
  Banner,
  Menu,
  MenuLocation,
  SectionKey,
  SectionOf,
  SiteSettings,
} from "@/lib/validations/content";

export const defaultSettings: SiteSettings = {
  businessName: "AG Appliance Services",
  brandLine1: "AG APPLIANCE",
  brandLine2: "SERVICES",
  tagline: "RELIABLE • QUALITY • TRUSTED",
  phone: "9123667075",
  whatsapp: "919123667075",
  email: "appliance26technician.ag@gmail.com",
  address: "Kolkata, West Bengal, India",
  hours: "8 AM – 9 PM, All Days",
  since: "2026",
  logo: "/images/logo.png",
  footerAbout:
    "Reliable home appliance repair service in Kolkata. Fast, affordable & trusted by hundreds of happy customers. Reliable • Quality • Trusted — Since 2026.",
  social: {
    facebook: "#",
    instagram: "#",
    whatsapp: "https://wa.me/919123667075",
    google: "#",
  },
  googleBusinessUrl: "#",
  copyright: "AG Appliance Services. All Rights Reserved.", // year is prefixed dynamically at render
  legalText: "Privacy Policy • Terms & Conditions",
  seoTitle: "AG Appliance Services — Appliance Repair Service in Kolkata",
  seoDescription:
    "Expert technicians for AC, Refrigerator, Geyser, Microwave & more — right at your doorstep in Kolkata. Same-day service with 100% customer satisfaction.",
};

export const defaultMenus: Record<MenuLocation, Menu> = {
  header: {
    location: "header",
    // same order as the sections on the page
    items: [
      { id: "home", label: "Home", href: "#home", visible: true, children: [] },
      {
        id: "services",
        label: "Services",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "steps",
        label: "How It Works",
        href: "#how-it-works",
        visible: true,
        children: [],
      },
      {
        id: "testimonials",
        label: "Reviews",
        href: "#testimonials",
        visible: true,
        children: [],
      },
      {
        id: "gallery",
        label: "Gallery",
        href: "#gallery",
        visible: true,
        children: [],
      },
      {
        id: "areas",
        label: "Areas",
        href: "#areas",
        visible: true,
        children: [],
      },
      { id: "faqs", label: "FAQs", href: "#faqs", visible: true, children: [] },
    ],
  },
  footerQuick: {
    location: "footerQuick",
    title: "Quick Links",
    items: [
      { id: "home", label: "Home", href: "#home", visible: true, children: [] },
      {
        id: "services",
        label: "Services",
        href: "#services",
        visible: true,
        children: [],
      },
      { id: "faqs", label: "FAQs", href: "#faqs", visible: true, children: [] },
      {
        id: "book",
        label: "Book Service",
        href: "#book",
        visible: true,
        children: [],
      },
    ],
  },
  footerServices: {
    location: "footerServices",
    title: "Our Services",
    items: [
      {
        id: "window-ac",
        label: "Window AC Repairing & Service",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "split-ac",
        label: "Split AC Repairing & Service",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "fridge",
        label: "Refrigerator Repairing & Service",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "deep-freezer",
        label: "Deep Freezer Repairing & Service",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "geyser",
        label: "Geyser Repair",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "micro",
        label: "Microwave Oven Repair",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "mixer",
        label: "Mixer Grinder Repair",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "induction",
        label: "Induction Cooktop Repair",
        href: "#services",
        visible: true,
        children: [],
      },
      {
        id: "pcb",
        label: "PCB & Electrical Repair",
        href: "#services",
        visible: true,
        children: [],
      },
    ],
  },
};

export const defaultBanners: Banner[] = [
  {
    tag: "RELIABLE • QUALITY • TRUSTED",
    heading: "Appliance Repair\nService in",
    headingAccent: "Kolkata",
    text: "Expert technicians for AC, Refrigerator, Geyser, Microwave & more — right at your doorstep. Same-day service with 100% customer satisfaction.",
    primaryCta: { label: "📅 Book Service", href: "#book" },
    secondaryCta: { label: "📞 9123667075", href: "tel:9123667075" },
    image: "/images/technician.jpg",
    images: [
      "/images/gallery-3.jpg",
      "/images/gallery-1.jpg",
      "/images/gallery-5.jpg",
      "/images/tools.jpg",
    ],
    imagePosition: "60% 30%",
    badgeText: "SAME-DAY SERVICE",
    cardTitle: "EXPERT TECHNICIANS",
    cardText: "Ready to fix your appliances",
    trust: [
      { icon: "tool", label: "Expert\nTechnicians" },
      { icon: "clock", label: "On-time\nService" },
      { icon: "rupee", label: "Affordable\nPricing" },
      { icon: "thumbs", label: "100% Customer\nSatisfaction" },
    ],
    order: 0,
    active: true,
  },
];

export const defaultSections: { [K in SectionKey]: SectionOf<K> } = {
  stats: {
    key: "stats",
    visible: true,
    items: [
      { icon: "users", value: "6+", label: "Years of\nExperience" },
      { icon: "shield", value: "13+", label: "Happy\nCustomers" },
      { icon: "pin", value: "26+", label: "Areas We\nServe" },
      { icon: "headset", value: "100%", label: "Satisfaction\nGuarantee" },
    ],
  },
  services: {
    key: "services",
    pill: "Our Services",
    heading: "Appliance",
    headingAccent: "Repair Services",
    subtitle:
      "From AC repair to fridge maintenance — we fix all major home appliances at your doorstep at the best price.",
    visible: true,
    items: [
      {
        icon: "ac",
        title: "AC Repair & Service",
        subtitle: "Split, Inverter & Window AC",
        href: "#book",
      },
      {
        icon: "fridge",
        title: "Refrigerator Repair",
        subtitle: "Cooling, Gas Charging, Compressor",
        href: "#book",
      },
      {
        icon: "geyser",
        title: "Geyser Repair",
        subtitle: "Heating, Thermostat, Leakage",
        href: "#book",
      },
      {
        icon: "microwave",
        title: "Microwave Oven Repair",
        subtitle: "Solo, Grill & Convection",
        href: "#book",
      },
      {
        icon: "mixer",
        title: "Mixer Grinder Repair",
        subtitle: "Motor, Coupler & Wiring",
        href: "#book",
      },
      {
        icon: "induction",
        title: "Induction Cooktop Repair",
        subtitle: "Heating & Display Issues",
        href: "#book",
      },
      {
        icon: "pcb",
        title: "PCB & Electrical Repair",
        subtitle: "All Appliance Circuit Boards",
        href: "#book",
      },
      {
        icon: "install",
        title: "AC Installation & Gas Charging",
        subtitle: "Installation, Cleaning, Uninstall",
        href: "#book",
      },
    ],
  },
  serviceCategories: {
    key: "serviceCategories",
    visible: true,
    items: [
      {
        icon: "snow",
        title: "AC Services",
        chips: [
          "Split AC",
          "Inverter AC",
          "Window AC",
          "Installation",
          "Service",
          "Cleaning",
          "Repair",
          "Cooling Problem",
          "Water Leakage",
          "Gas Charging",
          "PCB & Electrical Repair",
        ],
      },
      {
        icon: "fridge",
        title: "Refrigerator Services",
        chips: [
          "Cooling Problem",
          "Gas Charging",
          "Electrical Repair",
          "PCB Repair",
          "Compressor",
          "Thermostat",
          "Single / Double Door",
          "All Types",
        ],
      },
      {
        icon: "cog",
        title: "Other Appliance Services",
        chips: [
          "Mixer Grinder",
          "Geyser",
          "Microwave Oven",
          "Induction Cooktop",
          "PCB & Electrical Repair",
        ],
      },
    ],
  },
  why: {
    key: "why",
    pill: "Why Choose Us",
    heading: "Why Kolkata Trusts",
    headingAccent: "AG Appliance Services",
    visible: true,
    items: [
      {
        icon: "clock",
        title: "Same-Day Service",
        text: "We value your time. Get your appliance fixed on the same day.",
      },
      {
        icon: "shield",
        title: "90-Day Warranty",
        text: "All our repairs come with a 90-day service warranty.",
      },
      {
        icon: "rupee",
        title: "Affordable Pricing",
        text: "Top-quality service at transparent and affordable prices.",
      },
      {
        icon: "user",
        title: "Expert Technicians",
        text: "Skilled & certified professionals with years of experience.",
      },
      {
        icon: "home",
        title: "Doorstep Service",
        text: "We come to you. Hassle-free repairs at your location.",
      },
      {
        icon: "list",
        title: "All Brands Covered",
        text: "We repair all major brands of home appliances.",
      },
    ],
  },
  steps: {
    key: "steps",
    pill: "How It Works",
    heading: "Get Your Appliance Fixed in",
    headingAccent: "3 Easy Steps",
    visible: true,
    items: [
      {
        icon: "phone",
        title: "Book a Service Call",
        text: "Call us or book online with your appliance details.",
      },
      {
        icon: "user",
        title: "Technician Visits",
        text: "Our expert technician visits your location and diagnoses the issue.",
      },
      {
        icon: "gear",
        title: "Get It Fixed",
        text: "We fix your appliance on the spot and ensure it works perfectly.",
      },
    ],
  },
  video: {
    key: "video",
    pill: "WATCH HOW WE WORK",
    heading: "See Our Experts Fix Appliances",
    headingAccent: "Right at Your Doorstep",
    subtitle:
      "Our certified technicians diagnose, repair and test your AC, fridge and kitchen appliances at your home — book your visit in under a minute.",
    image: "/images/gallery-3.jpg",
    video: "/video/how-we-work.mp4",
    primaryCta: { label: "📞 Call Us Now", href: "tel:9123667075" },
    secondaryCta: { label: "📅 Book A Service", href: "#book" },
    visible: true,
  },
  testimonials: {
    key: "testimonials",
    pill: "What Our Customers Say",
    heading: "Happy Customers,",
    headingAccent: "Happy Us",
    visible: true,
    items: [
      {
        quote:
          "Excellent service! Technician arrived on time and fixed my split AC cooling problem perfectly.",
        name: "Arijit Sen",
        location: "Salt Lake, Kolkata",
        rating: 5,
      },
      {
        quote:
          "Very professional and courteous team. My fridge is running like new now after gas charging.",
        name: "Pooja Das",
        location: "New Town",
        rating: 5,
      },
      {
        quote:
          "Quick response and affordable service. Fixed my geyser the same day. Highly recommended!",
        name: "Rohit Bhattacharya",
        location: "Behala",
        rating: 5,
      },
      {
        quote:
          "They repaired my microwave within an hour. Transparent pricing and great workmanship.",
        name: "Sneha Mukherjee",
        location: "Rajarhat",
        rating: 5,
      },
    ],
  },
  gallery: {
    key: "gallery",
    pill: "Our Work",
    heading: "Recent Work",
    headingAccent: "Gallery",
    subtitle:
      "A glimpse of our technicians in action and the appliances we bring back to life every day.",
    visible: true,
    tabs: ["All", "AC", "Refrigerator", "Kitchen Appliances", "Our Team"],
    items: [
      {
        image: "/images/technician.jpg",
        chip: "ELECTRICAL REPAIR",
        title: "On-site Electrical & PCB Repair",
        subtitle: "Salt Lake, Kolkata",
        category: "AC",
        size: "big",
        feature: true,
      },
      {
        image: "/images/gallery-1.jpg",
        chip: "MICROWAVE",
        title: "Microwave Oven Service",
        subtitle: "Solo, Grill & Convection",
        category: "Kitchen Appliances",
        size: "normal",
        feature: false,
      },
      {
        image: "/images/gallery-2.jpg",
        chip: "REFRIGERATOR",
        title: "Fridge Cooling Repair",
        subtitle: "Gas charging & compressor",
        category: "Refrigerator",
        size: "tall",
        feature: false,
      },
      {
        image: "/images/gallery-5.jpg",
        chip: "OUR TEAM",
        title: "Certified Technician",
        subtitle: "Ready at your doorstep",
        category: "Our Team",
        size: "normal",
        feature: false,
      },
      {
        image: "/images/gallery-3.jpg",
        chip: "KITCHEN",
        title: "Complete Kitchen Appliance Care",
        subtitle: "Chimney, hob, microwave",
        category: "Kitchen Appliances",
        size: "wide",
        feature: false,
      },
      {
        image: "/images/tools.jpg",
        chip: "WORKSHOP",
        title: "Precision Tools & Genuine Parts",
        subtitle: "Quality workmanship",
        category: "Our Team",
        size: "normal",
        feature: false,
      },
      {
        image: "/images/gallery-7.jpg",
        chip: "REFRIGERATOR",
        title: "Vintage Fridge Restored",
        subtitle: "All types serviced",
        category: "Refrigerator",
        size: "normal",
        feature: false,
      },
    ],
  },
  brands: {
    key: "brands",
    pill: "Brands We Service",
    heading: "All Major Brands, One",
    headingAccent: "Expert Service",
    subtitle: "Authorized & experienced with all major appliance brands.",
    visible: true,
    items: [
      ["LG", "lg"],
      ["Samsung", "samsung"],
      ["Voltas", "voltas"],
      ["Daikin", "daikin"],
      ["Hitachi", "hitachi"],
      ["Carrier", "carrier"],
      ["Lloyd", "lloyd"],
      ["O General", "fujitsu-general"],
      ["Mitsubishi Electric", "mitsubishi-electric"],
      ["Panasonic", "panasonic"],
      ["Whirlpool", "whirlpool"],
      ["Godrej", "godrej"],
      ["Haier", "haier"],
      ["Bosch", "bosch"],
      ["Siemens", "siemens"],
      ["IFB", "ifb"],
      ["Toshiba", "toshiba"],
      ["Sharp", "sharp"],
      ["Electrolux", "electrolux"],
      ["Liebherr", "liebherr"],
      ["Midea", "midea"],
      ["Gree", "gree"],
      ["Hisense", "hisense"],
      ["TCL", "tcl"],
      ["Sony", "sony"],
      ["Onida", "onida"],
      ["Videocon", "videocon"],
      ["Xiaomi", "xiaomi"],
      ["Philips", "philips"],
      ["Bajaj", "bajaj"],
      ["Prestige", "prestige"],
      ["Butterfly", "butterfly"],
      ["Sujata", "sujata"],
      ["Crompton", "crompton"],
      ["Havells", "havells"],
      ["Orient Electric", "orient"],
      ["V-Guard", "vguard"],
      ["Kent", "kent"],
      ["Eureka Forbes", "eureka-forbes"],
      ["A. O. Smith", "aosmith"],
      ["Croma", "croma"],
      ["Elica", "elica"],
      ["Intex", "intex"],
      ["Micromax", "micromax"],
      ["Sansui", "sansui"],
      ["Beko", "beko"],
      ["Miele", "miele"],
      ["AEG", "aeg"],
      ["Smeg", "smeg"],
      ["Dyson", "dyson"],
      ["Hoover", "hoover"],
      ["Gorenje", "gorenje"],
      ["Indesit", "indesit"],
    ].map(([name, slug]) => ({ name, logo: `/brands/${slug}.svg` })),
  },
  areas: {
    key: "areas",
    pill: "We Serve All Across",
    heading: "Proudly Serving All Over",
    headingAccent: "Kolkata",
    visible: true,
    // north Kolkata + the Barrackpore–Kalyani belt (see components/site/areas-map.tsx for pins)
    items: [
      "Kalyani",
      "Kanchrapara",
      "Naihati",
      "Jagaddal",
      "Shyamnagar",
      "Ichapur",
      "Barrackpore",
      "Titagarh",
      "Khardah",
      "Sodepur",
      "New Barrackpore",
      "Belghoria",
      "Baranagar",
      "Birati",
      "Airport",
      "Kaikhali",
      "Kestopur",
      "Lake Town",
      "Rajarhat",
      "New Town",
      "Salt Lake",
      "Bidhannagar",
      "Tala",
      "Bagbazar",
      "Shyambazar",
      "Sovabazar",
    ].map((name) => ({ name })),
  },
  faqs: {
    key: "faqs",
    pill: "FAQs",
    heading: "Frequently Asked",
    headingAccent: "Questions",
    visible: true,
    items: [
      {
        question: "Do you provide same-day service?",
        answer:
          "Yes. Book before 2 PM and in most Kolkata areas our technician reaches you the same day.",
      },
      {
        question: "Do you charge for the visit?",
        answer:
          "A nominal inspection charge applies, which is fully adjusted against the repair bill if you proceed.",
      },
      {
        question: "What appliances do you repair?",
        answer:
          "AC, refrigerator, geyser, microwave oven, mixer grinder, induction cooktop and appliance PCB / electrical faults.",
      },
      {
        question: "Do you use original spare parts?",
        answer:
          "We use genuine or OEM-grade spare parts and share the part details with you before replacement.",
      },
      {
        question: "Are your technicians certified?",
        answer:
          "All technicians are trained, background-verified and experienced with every major brand.",
      },
      {
        question: "How can I book a service?",
        answer:
          "Call or WhatsApp 9123667075, or use the Book Service button on this page.",
      },
      {
        question: "What is the service warranty?",
        answer:
          "Every repair carries a 90-day service warranty on the work done.",
      },
      {
        question: "What payment methods do you accept?",
        answer: "Cash, UPI (Google Pay, PhonePe, Paytm) and bank transfer.",
      },
      {
        question: "How much does AC gas charging cost?",
        answer:
          "It depends on the AC type and gas; we quote a fixed price after inspection — no hidden charges.",
      },
      {
        question: "Do you repair all brands?",
        answer:
          "Yes — LG, Samsung, Voltas, Daikin, Whirlpool, Godrej, Haier, Bosch, IFB and many more.",
      },
    ],
  },
  cta: {
    key: "cta",
    heading: "Need an Appliance Fixed?",
    subtitle: "Call us now or book online. We are ready to help you!",
    primaryCta: { label: "Book Service Now", href: "#book" },
    secondaryCta: { label: "📞 9123667075", href: "tel:9123667075" },
    visible: true,
  },
};
