/**
 * SEO helpers: page metadata + JSON-LD structured data built from CMS content.
 * Author: Avijit Ghosh
 */
import { env } from "@/lib/env";
import type { SiteContent, SiteSettings } from "@/lib/validations/content";

import type { Metadata } from "next";

export const SITE_URL = env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, "");

const KEYWORDS = [
  "appliance repair Kolkata",
  "AC repair Kolkata",
  "AC service Kolkata",
  "refrigerator repair Kolkata",
  "fridge repair Kolkata",
  "geyser repair Kolkata",
  "microwave repair Kolkata",
  "mixer grinder repair",
  "induction cooktop repair",
  "PCB repair",
  "same day appliance repair",
  "doorstep appliance service",
  "AG Appliance Services",
];

export function buildHomeMetadata(settings: SiteSettings): Metadata {
  const title = settings.seoTitle;
  const description = settings.seoDescription;
  return {
    title: { absolute: title },
    description,
    keywords: KEYWORDS,
    alternates: { canonical: "/" },
    openGraph: {
      type: "website",
      locale: "en_IN",
      url: "/",
      siteName: settings.businessName,
      title,
      description,
      // /opengraph-image is generated by src/app/opengraph-image.tsx
    },
    twitter: { card: "summary_large_image", title, description },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    other: { "geo.region": "IN-WB", "geo.placename": "Kolkata" },
  };
}

const isRealUrl = (u: string | undefined): u is string => Boolean(u && /^https?:\/\//.test(u));

/** schema.org LocalBusiness — powers the Google Business rich result. */
export function localBusinessJsonLd(content: SiteContent) {
  const { settings, sections } = content;
  const [openH, closeH] = ["08:00", "21:00"]; // matches settings.hours "8 AM – 9 PM, All Days"
  return {
    "@context": "https://schema.org",
    "@type": ["LocalBusiness", "HomeAndConstructionBusiness"],
    "@id": `${SITE_URL}/#business`,
    name: settings.businessName,
    url: SITE_URL,
    image: `${SITE_URL}${settings.logo}`,
    logo: `${SITE_URL}${settings.logo}`,
    description: settings.seoDescription,
    telephone: `+91${settings.phone}`,
    email: settings.email,
    priceRange: "₹₹",
    foundingDate: settings.since,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kolkata",
      addressRegion: "West Bengal",
      addressCountry: "IN",
    },
    areaServed: sections.areas.items
      .map((a) => a.name)
      .filter((n) => !/more/i.test(n))
      .map((name) => ({ "@type": "Place", name: `${name}, Kolkata` })),
    openingHoursSpecification: {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
      opens: openH,
      closes: closeH,
    },
    sameAs: Object.values(settings.social).concat(settings.googleBusinessUrl).filter(isRealUrl),
    makesOffer: sections.services.items.map((s) => ({
      "@type": "Offer",
      itemOffered: { "@type": "Service", name: s.title, description: s.subtitle },
    })),
    aggregateRating: sections.testimonials.items.length
      ? {
          "@type": "AggregateRating",
          ratingValue: (
            sections.testimonials.items.reduce((a, t) => a + t.rating, 0) /
            sections.testimonials.items.length
          ).toFixed(1),
          reviewCount: sections.testimonials.items.length,
        }
      : undefined,
  };
}

/** schema.org FAQPage — eligible for FAQ rich results. */
export function faqJsonLd(content: SiteContent) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: content.sections.faqs.items.map((f) => ({
      "@type": "Question",
      name: f.question,
      acceptedAnswer: { "@type": "Answer", text: f.answer },
    })),
  };
}

export function websiteJsonLd(settings: SiteSettings) {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    url: SITE_URL,
    name: settings.businessName,
    inLanguage: "en-IN",
    publisher: { "@id": `${SITE_URL}/#business` },
  };
}

/** Safe to inline in a <script type="application/ld+json">. */
export function jsonLdString(data: unknown): string {
  return JSON.stringify(data).replace(/</g, "\\u003c");
}
